/* -------------------------------------------------------------------------- */
/* Injecting SVG into the DOM */
/* -------------------------------------------------------------------------- */

// The only place in the plugin that turns a string of SVG markup into DOM nodes. The inputs are either embedded
// constants (logos, pictograms: brand-assets.ts), or Scryfall SVGs (already passed through sanitizeSvg,
// api/scryfall.ts, before being cached), or markup generated by the plugin from numbers (charts), or — the only
// case really not under control — the ribbon icon chosen by the user (customIconSvg).
//
// This is no longer `el.innerHTML = svg` (rejected by the review of Obsidian's plugin directory): the string is
// parsed by DOMParser in an inert document, then the nodes are REBUILT one by one, only those of an allow-list
// (elements, attributes). Nothing is re-serialized, so nothing can be reinterpreted (no mXSS), and what isn't
// listed disappears: <script>, <style>, <foreignObject>, <a>, <image>, <use>, animations, on* attributes, href,
// style, comments. The parsing remains that of HTML (like innerHTML): an <svg> without xmlns, which is what the
// charts generate, remains an <svg>.
//
// List established on the 470 SVGs really injected (84 symbols and 365 Scryfall set icons, logos, flags,
// pictograms; tools/harness/ab/svg-markup.html): svg, g, path, rect, circle, defs, linearGradient, stop — and
// text/line/path/circle of the charts, including vector-effect (the price history stroke keeps its thickness
// despite preserveAspectRatio="none": forgotten at first, it's the A/B bench that showed it). The rest of the
// list covers the usual shapes and text of an SVG icon supplied by the user, no more.
//
// Accepted consequence: a ribbon icon that relies on a <style> or a style attribute (Illustrator export with
// st0/st1 classes) loses its colors; that <style> was in any case not limited to its <svg> (a global rule over
// the whole plugin, see the comment in brand-assets.ts).

const SVG_NS = "http://www.w3.org/2000/svg";

const ALLOWED_ELEMENTS = new Set([
	"svg", "g", "defs", "title", "desc",
	"path", "rect", "circle", "ellipse", "line", "polyline", "polygon",
	"text", "tspan",
	"linearGradient", "radialGradient", "stop", "clipPath", "mask",
]);

const ALLOWED_ATTRIBUTES = new Set([
	// structure
	"xmlns", "version", "id", "class", "role", "viewBox", "preserveAspectRatio", "transform",
	// geometry
	"x", "y", "x1", "x2", "y1", "y2", "cx", "cy", "r", "rx", "ry", "fx", "fy", "width", "height", "d", "points", "dx", "dy",
	// gradients, masks
	"gradientTransform", "gradientUnits", "spreadMethod", "offset", "clipPathUnits", "maskUnits", "maskContentUnits",
	// presentation
	"fill", "fill-opacity", "fill-rule", "clip-rule", "clip-path", "mask", "opacity", "isolation", "vector-effect", "shape-rendering",
	"stroke", "stroke-width", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-dasharray", "stroke-dashoffset", "stroke-opacity",
	"stop-color", "stop-opacity",
	// texte
	"text-anchor", "dominant-baseline", "font-family", "font-size", "font-weight", "letter-spacing",
]);

// An accepted attribute name: one from the list, or data-*/aria-* (inert).
function isAllowedAttributeName(name: string): boolean {
	return ALLOWED_ATTRIBUTES.has(name) || /^(data|aria)-[a-z0-9_.-]+$/i.test(name);
}

// An accepted value: any url(...) reference only points to an identifier of the same SVG ("url(#id)", that of
// the gradients). No external resource can be loaded by a presentation attribute.
function isSafeAttributeValue(value: string): boolean {
	for (const match of value.matchAll(/url\(\s*['"]?\s*([^)'"]*)/gi)) {
		if (!match[1].trim().startsWith("#")) return false;
	}
	return true;
}

function cloneAllowed(node: Node, doc: Document): Node | null {
	if (node.nodeType === Node.TEXT_NODE) return doc.createTextNode(node.nodeValue ?? "");
	// Comments, instructions (<?xml … ?>), everything else: never useful for display.
	if (node.nodeType !== Node.ELEMENT_NODE) return null;
	const source = node as Element;
	if (source.namespaceURI !== SVG_NS || !ALLOWED_ELEMENTS.has(source.localName)) return null;

	const copy = doc.createElementNS(SVG_NS, source.localName);
	for (const attr of Array.from(source.attributes)) {
		if (!isAllowedAttributeName(attr.name) || !isSafeAttributeValue(attr.value)) continue;
		// xmlns is the only namespaced attribute of the list (that of xmlns itself): the HTML parsing puts it in the
		// XMLNS namespace, it is copied as is so that the DOM is the one innerHTML produced.
		if (attr.namespaceURI) copy.setAttributeNS(attr.namespaceURI, attr.name, attr.value);
		else copy.setAttribute(attr.name, attr.value);
	}
	for (const child of Array.from(source.childNodes)) {
		const clean = cloneAllowed(child, doc);
		if (clean) copy.appendChild(clean);
	}
	return copy;
}

export function setSvgMarkup(el: HTMLElement, svg: string): void {
	const parsed = new DOMParser().parseFromString(svg, "text/html");
	const nodes: Node[] = [];
	for (const node of Array.from(parsed.body.childNodes)) {
		const clean = cloneAllowed(node, el.ownerDocument);
		if (clean) nodes.push(clean);
	}
	el.replaceChildren(...nodes);
}
